language: java
dist: trusty
jdk:
  - openjdk8
  - openjdk11
before_install:
  - chmod +x mvnw
os:
  - linux
script: "mvn clean package"
branches:
  except:
    - travis
notifications:
  email: wagnercct2@gmail.com
after_success:
  - mvn clean install