server:
  port: 1337

sentry.dsn: ${SENTRY_DSN:#{null}}

swagger.version: "1.0.0"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always